os:
  - linux

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - build-essential
      - make
      - cmake
      - libx11-dev
      - libxrandr-dev
      - libasound2-dev
      - git

script:
  - git clone https://github.com/Urho3D/Urho3D
  - cd Urho3D && cmake . && make && cd ..
  - qmake heXon.pro
  - make
