os:
  - linux

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - build-essential
      - make
      - g++-4.9
      - cmake
      - cmake-data
      - libx11-dev
      - libxrandr-dev
      - libasound2-dev
      - git

script:
  - git clone https://github.com/Urho3D/Urho3D
  - cd Urho3D
  - cmake . && make
  - cd ..
  - qmake heXon.pro
  - make
